name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: dev-firefox
    - name: Create Firefox Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'dev-firefox.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig /*releases/*'
